/** The guides for getting started and for the work itself (Start, Work, Learn). Brief on purpose: what it is for, then the steps. Checked by tests/help-docs.spec.ts. */
import type { HelpTopic } from './help-docs'

export const CORE_TOPICS: readonly HelpTopic[] = [
  {
    id: 'tour',
    title: 'Your first five minutes',
    group: 'Start',
    summary: 'what the console is, and the three things to know',
    steps: [
      { text: 'The console is the ruflo cockpit inside Claude Code. Every page is a number or a letter key: 0 is the main menu.', go: { view: 'menu' }, label: 'Open the main menu' },
      { text: 'Press p for the palette: type a few letters of anything you want to do, then Enter.', },
      { text: 'Press ✦ (Ask Claude) on any page to send that page to Claude with a question. It asks first.' },
      { text: 'Anything that changes something asks y or n first and shows the exact command. Reads run at once.' },
      { text: 'Press h on any page for the guide to that page. You are reading one now.' },
    ],
    tips: ['Lost? Press 0 for the menu. Stuck on a prompt? Press n.', 'Mouse works too: every key is also a button.'],
    related: ['concepts', 'setup', 'first-task'],
    keywords: ['begin', 'intro', 'overview', 'what is ruflo', 'basics', 'new'],
  },
  {
    id: 'concepts',
    title: 'How the pieces fit',
    group: 'Start',
    summary: 'model, skill, MCP and plugins: four things that are easy to confuse',
    steps: [
      { text: 'The model (Claude, GPT, Grok…) does the thinking. ruflo is not a model: it is the machinery around the work.' },
      { text: 'A skill is a playbook that teaches an agent how to approach a job. Installing one does not start a server or open your files.', go: { view: 'skills' } },
      { text: 'MCP is how an assistant finds and calls tools. When the ruflo MCP server is connected, the assistant can ask it for things like a health check or a memory search.' },
      { text: 'Plugins package more: skills, commands, agents and hooks that react to events. “I installed the skill” and “the MCP server is connected” are two different facts.', go: { view: 'market' }, label: 'Browse plugins' },
      { text: 'A swarm is several focused agents sharing one goal. It helps when work can be divided; for a two-line edit, one agent is better.' },
    ],
    tips: ['Start with one useful task and add more only when it earns its place.', 'The full explainer is docs/ruflo-explained.md in the ruflo repository.'],
    related: ['connect', 'first-task', 'swarm'],
    keywords: ['what is ruflo', 'mcp', 'skill', 'model', 'difference', 'explain', 'workshop', 'concepts', 'terms'],
  },
  {
    id: 'connect',
    title: 'Connect ruflo to your assistant',
    group: 'Start',
    summary: 'Claude Code, Codex, Claude Desktop, ChatGPT or Grok: pick one path',
    steps: [
      { text: 'Claude Code, packaged: run /plugin marketplace add ruvnet/ruflo, then /plugin install ruflo-core@ruflo. Add ruflo-swarm or ruflo-rag-memory when you need them.', go: { view: 'plugins' }, label: 'Check plugins' },
      { text: 'Claude Code, direct: claude mcp add ruflo -- npx --yes ruflo mcp start, then claude mcp list. Choose one path; two copies of the server confuse tool discovery.' },
      { text: 'Codex: codex mcp add ruflo -- npx --yes ruflo mcp start, then codex mcp list. Or run npx ruflo init --codex in a disposable project first.' },
      { text: 'Claude Desktop has its own config: merge a ruflo entry (command npx, args --yes ruflo mcp start) into mcpServers, restart it, and check the tools appear.' },
      { text: 'ChatGPT on the web needs a remote, authenticated MCP URL, not a local command. Never expose a local server to the internet without authentication.' },
      { text: 'Grok CLI: grok mcp add ruflo -- npx --yes ruflo mcp start, then grok mcp doctor ruflo.' },
    ],
    tips: ['Pin a version (ruflo@x.y.z) if you want the same release every time.', 'Success is one real call that returns a result, not a config entry.'],
    related: ['verify', 'plugins', 'concepts'],
    keywords: ['claude code', 'codex', 'desktop', 'chatgpt', 'grok', 'mcp', 'install', 'connect', 'register', 'client'],
  },
  {
    id: 'first-task',
    title: 'Your first real task',
    group: 'Start',
    summary: 'a safe, bounded review, then one agreed change, with evidence',
    steps: [
      { text: 'Use a small project with no secrets. Ask for a read-only review: summarise it, say how to run its tests, propose three independent review tasks. No edits, no installs, no deploy.' },
      { text: 'Read the plan. Then approve one specific change with a clear acceptance test and a stopping point.', go: { view: 'missions' }, label: 'Open Missions' },
      { text: 'Ask for the diff, the test results and the remaining risks. Stop before committing or deploying.' },
      { text: 'Run the same tests before and after. The deliverable is the change plus evidence, not a message saying done.' },
    ],
    tips: ['An agent saying “done” is not a test result.', 'Easier to debug than switching on dozens of agents at once.'],
    related: ['mission', 'verify', 'cost'],
    keywords: ['first', 'start', 'review', 'try', 'example', 'walkthrough', 'tutorial', 'evidence', 'acceptance'],
  },
  {
    id: 'keys',
    title: 'Keys and navigation',
    group: 'Start',
    summary: 'every key that works on every page',
    steps: [
      { text: '0 main menu · 1 missions · 2 overview · 3 swarm · 4 claims · 5 federation · 6 plugins · 7 learning · 8 metaharness · 9 memory.' },
      { text: 'Letters reach the rest: b hive · c cost · g timeline · q approvals · e events · w x.ruv.io · i terminal · z skills · u security · f performance · a automation · l learning lab · v vector lab · t self-evolution · d dev tools · m plugin catalog · s settings.' },
      { text: 'p palette · x actions for the selection · r refresh and replay the intro · h help · y / n confirm or cancel.' },
      { text: 'j / k move the selection · d drill into an agent · b back · f filters the events page.' },
      { text: 'On the main menu, type a key or a name in the prompt and press Enter. o logs off. Sandbox has no key: type sandbox, or find it under NETWORK in the nav.' },
    ],
    tips: ['In a text field, your keys type into the field.'],
    related: ['tour', 'headless'],
    keywords: ['keyboard', 'shortcuts', 'hotkeys', 'navigate'],
  },
  {
    id: 'setup',
    title: 'Set ruflo up in a project',
    group: 'Start',
    summary: 'three steps from nothing to a working swarm',
    steps: [
      { text: 'Initialise ruflo here. This creates .claude-flow and the mods. It asks first.', go: { start: 'init' } },
      { text: 'Start the daemon. It runs the background workers: map, audit, optimize, consolidate.', go: { start: 'daemon' } },
      { text: 'Start a swarm: hierarchical, up to 8 agents.', go: { start: 'swarm' } },
      { text: 'Open the Overview to see what is running and what needs attention.', go: { view: 'overview' } },
    ],
    tips: ['Each step shows ✔ on its page once the disk has it, so you can leave and come back.'],
    related: ['swarm', 'plugins', 'troubleshoot'],
    keywords: ['init', 'initialise', 'install', 'getting started', 'first time'],
  },
  {
    id: 'mission',
    title: 'Run a mission',
    group: 'Work',
    summary: 'give a goal; ruflo plans it, makes tasks, and Claude carries them out',
    steps: [
      { text: 'Type your goal in one sentence in the goal field (on the main menu or Missions) and press Enter.', go: { view: 'missions' }, label: 'Open Missions' },
      { text: 'ruflo plans it (research, create, build, test, validate, secure, benchmark, learn), makes the tasks, and asks Claude for guidance.' },
      { text: 'Missions lists the tasks: ● done  ◐ running  ○ ready  · waiting on another  ✖ failed  ⊘ cancelled.' },
      { text: 'Hand the next task to Claude, or turn on auto-run to hand them out one after another.' },
      { text: 'Pause or resume any time. Cancel stops the mission. Guide and aside ask Claude for help on it.' },
    ],
    tips: ['Small, clear goals work best. “Add rate limiting to the login route” beats “improve the API”.'],
    related: ['mission-loop', 'claims', 'swarm', 'approvals'],
    keywords: ['goal', 'plan', 'sparc', 'tasks', 'objective', 'project'],
  },
  {
    id: 'mission-loop',
    title: 'Drive a mission with a loop',
    group: 'Work',
    summary: 'a bounded /loop that checks, fixes and runs the gates until done',
    steps: [
      { text: 'Set the loop in Settings: the interval (5m by default), a worktree per writer, whether it may commit, push or publish (push and publish are off), and the most concurrent writers (6).', go: { view: 'settings' }, label: 'Open Settings' },
      { text: 'Enter your goal. The plan and Claude’s guidance now name the /loop line, each tick’s checklist, the gates, the finish condition and the stop rule.', go: { view: 'missions' }, label: 'Open Missions' },
      { text: 'Each tick the loop checks progress, fixes what failed, runs the gates and repeats until every phase is green. Writers work at once, each in its own worktree; defaults are stated up front, so it does not stop to ask.' },
      { text: 'On a long mission open its Loop tab. Start puts the /loop line in your prompt box (you press Enter); the console counts ticks, shows the next one and the time left, and warns before the 7-day expiry. Re-arm prepares a fresh one.', go: { view: 'missions' }, label: 'Open Missions' },
      { text: 'Verify runs your own gate commands (Settings → Mission gates). Each asks first, runs without a shell, and its exit code is recorded as evidence.' },
      { text: 'Set a spend cap in Settings: auto-run pauses when the mission reaches it. Spend is a list-price estimate from the cost ledger.' },
      { text: 'Nothing leaves the mission branch unless you turned it on: no push, no release, no deploy.' },
    ],
    tips: ['A fix is checked by breaking it once: the test must fail, then pass again.', 'The active task rides in Claude’s prompt (Settings → Mission context) and changes only when the task does, so the cache stays warm.'],
    related: ['mission', 'swarm', 'verify', 'cost'],
    keywords: ['loop', 'tick', 'interval', 'worktree', 'gates', 'finish', 'concurrent', 'writers', 'autopilot', 'defaults', 'long', 'expire', 're-arm', 'cap', 'verify', 'evidence'],
  },
  {
    id: 'swarm',
    title: 'Start a swarm and spawn agents',
    group: 'Work',
    summary: 'a team of agents with roles, working together',
    steps: [
      { text: 'Start a swarm (needs ruflo initialised).', go: { start: 'swarm' } },
      { text: 'Spawn a coder: it writes the code.', go: { start: 'spawn-coder' } },
      { text: 'Spawn a tester: it checks the work.', go: { start: 'spawn-tester' } },
      { text: 'Spawn a reviewer: it reviews the result.', go: { start: 'spawn-reviewer' } },
      { text: 'Open the Swarm page to see who is working, and the Timeline to see when.', go: { view: 'swarm' } },
    ],
    tips: ['Select an agent (j / k), then d, to see its task, claims, activity and logs.', 'More roles are in the palette: type spawn.'],
    related: ['claims', 'hive', 'watch'],
    keywords: ['agents', 'team', 'topology', 'spawn', 'roles'],
  },
  {
    id: 'hive',
    title: 'Hive-mind: decisions by vote',
    group: 'Work',
    summary: 'a queen and workers who vote, so no single agent decides alone',
    steps: [
      { text: 'Start a hive-mind: a queen with raft consensus.', go: { start: 'hive' } },
      { text: 'Spawn three workers. They are the voters.', go: { start: 'hive-workers' } },
      { text: 'On the Hive page, write a proposal and send it.', go: { view: 'hive' } },
      { text: 'Cast votes on the Approvals page. Quorum decides.', go: { view: 'approvals' } },
    ],
    tips: ['Raft tolerates up to half the workers failing; Byzantine mode tolerates under a third misbehaving.'],
    related: ['approvals', 'swarm'],
    keywords: ['queen', 'workers', 'consensus', 'raft', 'vote', 'quorum', 'proposal'],
  },
  {
    id: 'claims',
    title: 'Tasks and claims',
    group: 'Work',
    summary: 'one owner per task, so agents never do the same work twice',
    steps: [
      { text: 'Open Claims (key 4). Create a task: one line saying what must be done.', go: { view: 'claims' } },
      { text: 'Claim it. A claim has one owner, so no one else works on it.' },
      { text: 'Done or stuck? Release it, hand it off to another agent, or steal one that is stealable.' },
      { text: 'Every change asks y or n first and shows who gets what.' },
    ],
    related: ['swarm', 'mission'],
    keywords: ['task', 'owner', 'release', 'handoff', 'steal', 'board'],
  },
  {
    id: 'approvals',
    title: 'Answer pending decisions',
    group: 'Work',
    summary: 'votes, stealable claims, refused mods and budget asks in one place',
    steps: [
      { text: 'Open Approvals (key q). Each row is a decision waiting for you.', go: { view: 'approvals' } },
      { text: 'Select one (j / k) and read what it asks.' },
      { text: 'Press y to approve, n to refuse. Nothing happens until you do.' },
    ],
    tips: ['The main menu shows a badge when something is waiting.'],
    related: ['hive', 'claims'],
    keywords: ['vote', 'approve', 'waiting', 'confirm'],
  },
  {
    id: 'automation',
    title: 'Automate with workflows and workers',
    group: 'Work',
    summary: 'run work on a schedule or in the background, hands off',
    steps: [
      { text: 'Check the daemon is running: it hosts the 12 background workers.', go: { run: 'auto-daemon-status' } },
      { text: 'Open Automation (key a). Dispatch a worker such as audit, optimize or testgaps.', go: { view: 'automate' } },
      { text: 'List the workflows, or create one from a template.', go: { run: 'auto-wf-list' } },
      { text: 'Turn on autopilot to let ruflo pick the next step. Check it any time.', go: { run: 'auto-ap-status' } },
      { text: 'Use loops to repeat a task, or a sentry to find and fix bugs on a schedule.' },
    ],
    tips: ['Anything that changes something, or calls a model, asks first.'],
    related: ['security', 'learning'],
    keywords: ['schedule', 'workflow', 'worker', 'daemon', 'autopilot', 'loop', 'sentry', 'background'],
  },
  {
    id: 'terminal',
    title: 'The AI terminal',
    group: 'Work',
    summary: 'talk to claude -p or codex without leaving the console',
    steps: [
      { text: 'Open the Terminal (key i). The field takes your keys.', go: { view: 'terminal' } },
      { text: 'Type a message. The first one asks first, then Enter sends.' },
      { text: 'Switch with /claude, /codex or /swarm. /new starts over.' },
      { text: 'Sessions remember the conversation per project. Tab to s stops, o opens a new one, z clears.' },
    ],
    related: ['settings', 'cost'],
    keywords: ['claude', 'codex', 'chat', 'prompt', 'session'],
  },
  {
    id: 'watch',
    title: 'Watch what is happening',
    group: 'Work',
    summary: 'who is busy, what changed, and when',
    steps: [
      { text: 'Timeline (key g) shows each agent busy or idle over the last minutes.', go: { view: 'timeline' } },
      { text: 'Events (key e) lists every swarm, claim, memory and mod event as it happens.', go: { view: 'events' } },
      { text: 'Press f on Events to filter: swarm, claims, federation, learning, tools, mods, missions.' },
      { text: 'The band above the Claude prompt shows the live summary: tool activity, claims and cost.' },
    ],
    related: ['swarm', 'cost'],
    keywords: ['activity', 'log', 'events', 'timeline', 'monitor'],
  },
  {
    id: 'learning',
    title: 'Teach ruflo your repo',
    group: 'Learn',
    summary: 'ruflo learns which agent fits which job, from your own work',
    steps: [
      { text: 'Pretrain on this repo. It is local and shallow.', go: { start: 'pretrain' } },
      { text: 'Open Learning (key 7) to see the router’s picks and how they turned out.', go: { view: 'learning' } },
      { text: 'Open the Learning Lab (key l) to train patterns, watch the loss, and ask which agent fits a task.', go: { view: 'neural' } },
      { text: 'It improves as outcomes are recorded: what worked and what did not.' },
    ],
    tips: ['The pipeline is RETRIEVE, JUDGE, DISTILL, CONSOLIDATE. EWC++ stops it forgetting old lessons.'],
    related: ['memory', 'evolve'],
    keywords: ['train', 'neural', 'router', 'routing', 'patterns', 'sona', 'pretrain'],
  },
  {
    id: 'memory',
    title: 'Use memory',
    group: 'Learn',
    summary: 'store things once, find them by meaning later',
    steps: [
      { text: 'See what is stored: entries, size, oldest and newest.', go: { run: 'mem-stats' } },
      { text: 'Check AgentDB is healthy and which controllers are on.', go: { run: 'mem-health' } },
      { text: 'Open the Memory Lab (key 9). Search by meaning, not exact words.', go: { view: 'memory' } },
      { text: 'Store a note with a key; delete it any time. Deletes ask first.' },
    ],
    tips: ['Search matches by meaning, so it finds related entries even when the words differ.'],
    related: ['vector', 'learning'],
    keywords: ['agentdb', 'embeddings', 'recall', 'remember', 'store', 'search'],
  },
  {
    id: 'vector',
    title: 'Vector Lab',
    group: 'Learn',
    summary: 'work with ruvector directly: stores, queries, the shared brain',
    steps: [
      { text: 'Open the Vector Lab (key v).', go: { view: 'vector' } },
      { text: 'Browse the RVF stores and run a query against one.' },
      { text: 'Try rvlite for SQL, Cypher or SPARQL over a local file.' },
      { text: 'Anything that shares to the shared brain asks first.' },
    ],
    related: ['memory', 'learning'],
    keywords: ['ruvector', 'rvf', 'hnsw', 'rvlite', 'brain', 'similarity', 'index'],
  },
  {
    id: 'metaharness',
    title: 'Check your harness',
    group: 'Learn',
    summary: 'how ready the project is for agents, and what to fix first',
    steps: [
      { text: 'Score the harness: five readiness axes and the cost per run.', go: { run: 'mh-score' } },
      { text: 'Scan the MCP surface for security findings, by severity.', go: { run: 'mh-mcp-scan' } },
      { text: 'See the audit trend: the newest audit against the one before.', go: { run: 'mh-trend' } },
      { text: 'Open MetaHarness (key 8) for the lab that runs every verb.', go: { view: 'metaharness' } },
    ],
    related: ['security', 'evolve'],
    keywords: ['readiness', 'score', 'audit', 'flywheel', 'harness'],
  },
  {
    id: 'evolve',
    title: 'Self-evolution (governed)',
    group: 'Learn',
    summary: 'ruflo proposes improvements; you decide what is kept',
    steps: [
      { text: 'Open Self-Evolution (key t).', go: { view: 'evolve' } },
      { text: 'Read the receipts: each evaluated candidate, with its evidence.', go: { run: 'evolve-receipts' } },
      { text: 'Check the policy gate: what is allowed and what is not.', go: { run: 'evolve-gate' } },
      { text: 'Promote only what you trust, and only with a confirm. It cannot promote itself.' },
    ],
    tips: ['The ledger and the witness make every change traceable.'],
    related: ['metaharness', 'learning'],
    keywords: ['flywheel', 'receipts', 'lineage', 'promote', 'darwin', 'governed'],
  },
]
