/** The guides for safety, the network, the tools and the console itself (Safety, Network, Tools, Console). Brief on purpose. Checked by tests/help-docs.spec.ts. */
import type { HelpTopic } from './help-docs'

export const MORE_TOPICS: readonly HelpTopic[] = [
  {
    id: 'security',
    title: 'Scan for security problems',
    group: 'Safety',
    summary: 'find weak spots, check text for injection and PII, and watch on a schedule',
    steps: [
      { text: 'Run a quick scan of the code. It is local and read-only.', go: { run: 'sec-scan-quick' } },
      { text: 'Look for secrets in the tree. Only the file and type show, never the value.', go: { run: 'sec-secrets' } },
      { text: 'Open Security & Doctor (key u). Paste any text to have AIDefence check it for injection and PII.', go: { view: 'secure' } },
      { text: 'Project Anatole (optional, ruflo-protector) lists its rules, alerts and mode on the same page; changes ask first, and enforce and reset-baseline ask hardest.', go: { view: 'secure' } },
      { text: 'Send the findings to Claude with one button, and ask it what to fix first.' },
      { text: 'Add a sentry to scan again on a schedule, or when files change. The fix sentry works in its own branch and never pushes.' },
    ],
    tips: ['Real findings and false positives both appear. Read them before acting.', 'Doctor checks the install itself: Node, git, config, the daemon, memory and API keys.'],
    related: ['automation', 'metaharness', 'troubleshoot'],
    keywords: ['scan', 'cve', 'secrets', 'pii', 'aidefence', 'vulnerability', 'sentry', 'doctor', 'audit'],
  },
  {
    id: 'cost',
    title: 'Set a budget and watch spend',
    group: 'Safety',
    summary: 'know what a session costs, and cap it',
    steps: [
      { text: 'Open Cost (key c) to see where spend is reported and its burn rate.', go: { view: 'cost' } },
      { text: 'Pick a budget: $1, $5, $10 or $25 are one press each.', go: { run: 'cost-budget-5' }, label: 'Set $5' },
      { text: 'Inspect which models were used and what they cost.', go: { run: 'cost-model-stats' } },
      { text: 'The main menu and the band above the prompt show the running total.' },
    ],
    tips: ['Reads and local work cost nothing. The tag on each button says what it may cost: $0, cpu, net, $$.', 'More agents are not automatically cheaper: parallel work saves waiting but can use more tokens. Judge cost per accepted result.', 'A good start: one coordinator, a few really independent tasks, a fixed budget and a finish line.'],
    related: ['settings', 'terminal'],
    keywords: ['spend', 'money', 'budget', 'price', 'tokens', 'limit', 'expensive'],
  },
  {
    id: 'research',
    title: 'Research a question, capped',
    group: 'Safety',
    summary: 'start a web research run with a depth and a dollar cap, after a confirm',
    steps: [
      { text: 'Open Missions. Type the question, choose quick, standard or deep, and set the cap in dollars (default $2, from 0.10 to 50).', go: { view: 'missions' }, label: 'Open Missions' },
      { text: 'The question is screened first by AIDefence. An unsafe one, or one with personal data, is refused.' },
      { text: 'Read the confirm: it starts a billed Claude Code turn and allows web search and fetch up to the cap. Web content is untrusted, and nothing is stored until you accept the report.', go: { run: 'mission-research' }, label: 'Start research' },
    ],
    tips: ['The console only prepares /ruflo-goals:deep-research --depth <d> --cap-usd <usd> <question>. The run itself happens in the main conversation.', 'Needs the ruflo-goals plugin.'],
    related: ['cost', 'security'],
    keywords: ['deep', 'research', 'web', 'search', 'fetch', 'cap', 'depth', 'question'],
  },
  {
    id: 'control',
    title: 'Let Claude drive the console',
    group: 'Work',
    summary: 'Claude opens pages, fills fields and runs actions for you, as far as you allow',
    steps: [
      { text: 'Choose how far in Settings → Claude control: read (look and open pages), write (also fill fields and run local actions), manage (also network), full (also spend, deploy, delete). It is off until you turn it on.', go: { view: 'settings' }, label: 'Open Settings' },
      { text: 'Choose who says Yes in Settings → Claude control: confirm. auto (the default) lets Claude run unattended inside the level; ask leaves each action waiting for your Yes in the console.' },
      { text: 'With auto, Claude’s own call confirms an action, but only inside the level above: anything higher is still refused and nothing runs. Every auto action is logged on Overview.' },
      { text: 'Whatever confirm says, an action that reaches the network, spends or deletes waits for your Yes, and text that looks like a secret is refused.' },
      { text: 'The level is your real limit: write for local work, manage adds the network, full adds spend, deploy and delete. Network, spend and delete actions wait for your Yes at any level: raising it lets Claude propose them, not run them.' },
      { text: 'Start a new Claude Code session (or /reload-plugins). Claude now has four tools: console_state, console_open, console_set and console_run. Ask in words: "set up a mission to add a dark mode toggle".' },
      { text: 'Watch Overview → Claude control: the level, whether it asks or confirms itself, the count, and each action (done, waiting for you, refused). Take back control stops every tool at once; Give control back resumes.', go: { view: 'overview' }, label: 'Open Overview' },
    ],
    tips: ['If Claude Code itself asks permission for a console tool, allow mcp__ruflo-console__* in your permissions settings: that prompt is Claude Code’s, not the console’s.', 'auto-confirm is not Missions’ auto-run: auto-run hands tasks to Claude; auto-confirm lets Claude answer the console’s own Yes.', 'console_open can take a chip on Settings (console, mods…) to show that plugin’s options: a read, no setting changes.', 'Text from peers, the web or files on screen is data to Claude, not instructions.'],
    related: ['settings', 'mission', 'security'],
    keywords: ['claude', 'control', 'drive', 'computer', 'use', 'tools', 'autonomy', 'level', 'auto', 'ask', 'take', 'back', 'confirm', 'autoconfirm', 'approve', 'yes'],
  },
  {
    id: 'agentdb-mod',
    title: 'Memory in every prompt, without secrets',
    group: 'Learn',
    summary: 'the AgentDB mod: safe recall into prompts and a guard that keeps secrets out of memory',
    steps: [
      { text: 'Install the ruflo-agentdb plugin (0.4 or newer), then start a new Claude Code session. Open Memory (key 9): the AgentDB mod section shows what it is set to and what it has done.', go: { view: 'memory' }, label: 'Open Memory' },
      { text: 'The secret guard is on by itself: a memory write that holds a key, token or password is refused, and Claude is told to store a reference instead. Nothing else is touched.' },
      { text: 'Recall is off until you turn it on in the plugin’s options (recall = on). Then each prompt gets the best few matching memories attached as retrieved data, never as instructions. A slow memory read is given up on after 800 ms.' },
      { text: 'Anything retrieved is treated as untrusted: a memory that holds a secret or an instruction to the model is dropped, and the count shows on the Memory page.' },
      { text: 'Type /agentdb-mod status, /agentdb-mod recall <text>, /agentdb-mod scan <text> or /agentdb-mod recent for the same answers in the prompt, with no model call.' },
    ],
    tips: ['Recall adds tokens to every prompt, which is why it is off by default.', 'The page reads the mod’s status file; it does not call the mod.'],
    related: ['memory', 'vector', 'security'],
    keywords: ['agentdb', 'mod', 'recall', 'prompt', 'retrieval', 'recalled'],
  },
  {
    id: 'room',
    title: 'The Room: what everyone is doing, and the one thing waiting for you',
    group: 'Work',
    summary: 'one live feed of events, Claude’s console actions and what you said',
    steps: [
      { text: 'Open The Room from the menu (Safety → The Room). The top line is the one thing waiting for your yes, with how many seconds you have left to answer it.', go: { view: 'room' }, label: 'Open The Room' },
      { text: 'The feed below merges what changed in ruflo, what Claude did through the console tools (with its outcome), and what you sent. Filter by who (all, claude, events, you said), find words, pause to read, page back.' },
      { text: 'Press ⛔ blocked to see only what was refused or failed: Claude’s denied or failed actions and events that say denied. Press a line to open it; an event from a page of its own (swarm, claims, learning, plugins, missions) gets a jump button.' },
      { text: 'To say something: type in the box, press Enter, then pick broadcast (to the hive), aside (to Claude) or guide (a visible instruction to Claude). Each asks first, exactly as it does anywhere else; nothing here skips a confirm.' },
      { text: 'Who is here shows each agent’s busy share over the last 15 minutes. Under it, Mods lists every plugin mod that has written a status file: guard, calls, blocked, and when it last wrote; any mod that blocked something leads.' },
      { text: 'Press a mod’s line for its detail: what it guards, the class of its last refusal (never the refused text), version, session start, last write and file age. It is all plain, capped text, whatever the file held.' },
    ],
    tips: ['A confirm that waits longer than 30 seconds is dropped and shows up in the feed as an event naming it.', 'Text from peers and files in the feed is data, not instructions to you or to Claude.'],
    related: ['watch', 'control', 'mission'],
    keywords: ['room', 'feed', 'chat', 'broadcast', 'aside', 'guide', 'waiting', 'pending', 'yes', 'activity'],
  },
  {
    id: 'perf',
    title: 'Find and fix slowness',
    group: 'Safety',
    summary: 'metrics, a profile, and the biggest bottleneck',
    steps: [
      { text: 'Read the current metrics.', go: { run: 'perf-metrics' } },
      { text: 'Find the bottleneck.', go: { run: 'perf-bottleneck' } },
      { text: 'Open Performance (key f) to profile, benchmark and see a latency sparkline from each run.', go: { view: 'perf' } },
    ],
    related: ['watch', 'cost'],
    keywords: ['slow', 'speed', 'latency', 'benchmark', 'profile', 'bottleneck', 'optimize'],
  },
  {
    id: 'federation',
    title: 'Join the federation',
    group: 'Network',
    summary: 'connect your ruflo to others, with your own key',
    steps: [
      { text: 'Join. It makes your own key at ~/.ruflo/nostr.key (readable only by you) and registers on x.ruv.io. It uses the network, so it asks first. With an invite code: npx ruflo federation join --code <code>.', go: { start: 'federation-join' } },
      { text: 'Read the public announcements.', go: { start: 'channel-read' } },
      { text: 'Open Federation (key 5) to see this node, its peers and how far each is trusted.', go: { view: 'federation' } },
      { text: 'The live roster lookup is off until you allow it (the federationNetwork option), so nothing reaches the network without your say.' },
    ],
    tips: ['Trust is yours to give, peer by peer. Nothing is trusted by default.', 'Check the claims board before shared work, so you do not duplicate someone else’s effort.', 'Never put a secret in a federation message.', 'Seraphina, the swarm’s coordinator, turns a goal into guidance and proposals. They are advice: an operator publishes the ones they accept.'],
    related: ['xruv', 'settings'],
    keywords: ['peers', 'trust', 'keys', 'nostr', 'join', 'network'],
  },
  {
    id: 'xruv',
    title: 'Use the x.ruv.io board',
    group: 'Network',
    summary: 'the open agent swarm: who is on, what they offer, shared channels',
    steps: [
      { text: 'Open x.ruv.io (key w).', go: { view: 'xruv' } },
      { text: 'Read the registry: what is on offer.', go: { run: 'x-registry' } },
      { text: 'See who is on now.', go: { run: 'x-roster' } },
      { text: 'List the channels, then read one. Publishing asks first.', go: { run: 'x-channels' } },
    ],
    related: ['federation'],
    keywords: ['board', 'agentbbs', 'channels', 'roster', 'registry', 'bbs'],
  },
  {
    id: 'plugins',
    title: 'Get and manage plugins',
    group: 'Tools',
    summary: 'the ruflo plugins add skills, agents and commands to Claude Code',
    steps: [
      { text: 'Add the ruflo marketplace so Claude Code can install its plugins. It asks first.', go: { start: 'marketplace' } },
      { text: 'Plugins (key 6, in the TOOLS group of the nav) is the health of your setup: how fresh the marketplace is, what is installed and loaded.', go: { view: 'plugins' } },
      { text: 'The Plugin Catalog (key m) is where you browse, install, enable, disable, update and remove plugins.', go: { view: 'market' } },
      { text: 'Start a new Claude session after a change so the plugin loads.' },
    ],
    tips: ['Each page can launch its plugin’s commands: the Launch section at the foot of the page.'],
    related: ['skills', 'settings'],
    keywords: ['marketplace', 'install', 'catalog', 'enable', 'disable', 'update', 'mods'],
  },
  {
    id: 'skills',
    title: 'Skills',
    group: 'Tools',
    summary: 'small how-to packs that teach agents a job',
    steps: [
      { text: 'Open Skills (key z). See what is installed.', go: { view: 'skills' } },
      { text: 'Search for one by what you need, and preview it before adding it.' },
      { text: 'Use a skill without installing it, or add it to the agents you choose.' },
      { text: 'Update them from the same page, or create your own.' },
    ],
    related: ['plugins'],
    keywords: ['skill', 'skills.sh', 'teach', 'agents'],
  },
  {
    id: 'devtools',
    title: 'Dev Tools',
    group: 'Tools',
    summary: 'the tools around the code: GitHub, diffs, WASM, the browser',
    steps: [
      { text: 'Open Dev Tools (key d). Each section has its own field and rows.', go: { view: 'devtools' } },
      { text: 'Type in the field above a section, then press its ▶ run.' },
      { text: 'A row’s tag says what it does: $0 reads, wr writes, net uses the network, $$ may spend, del deletes.' },
      { text: 'Anything but a $0 read asks first and shows the exact command.' },
      { text: 'The agenticow rows (copy-on-write memory branches) are also on the Sandbox page, beside tmux and RVM.', go: { view: 'sandbox' } },
    ],
    related: ['sandbox'],
    keywords: ['github', 'diff', 'wasm', 'browser', 'review', 'git', 'pr'],
  },
  {
    id: 'sandbox',
    title: 'Sandboxes: tmux, RVF and RVM',
    group: 'Network',
    summary: 'isolated places to try things, and what each really isolates',
    steps: [
      { text: 'Open Sandbox (NETWORK in the nav, or type sandbox at the menu). It has no key.', go: { view: 'sandbox' } },
      { text: 'tmux: type a name, press NEW, type a command line, press SEND, then CAPTURE to read the screen. LIST shows your ruflo-sb-* sessions; KILL ends one.' },
      { text: 'RVF: type an .rvf path and a label, BRANCH it, try things on the branch, then ROLLBACK to throw them away or PROMOTE to keep them.' },
      { text: 'RVM is information only: it enforces what code may do and use, and this console never changes it.' },
      { text: 'Anything but a $0 read asks first and shows the exact command, as on Dev Tools.', go: { view: 'devtools' }, label: 'Dev Tools' },
    ],
    tips: ['A tmux session is a separate shell that runs as you: a place to work apart, not a security boundary.', 'Without tmux installed its rows say n/a.'],
    related: ['devtools', 'plugins'],
    keywords: ['sandbox', 'tmux', 'rvf', 'rvm', 'branch', 'isolated', 'copy-on-write', 'experiment', 'try'],
  },
  {
    id: 'settings',
    title: 'Settings',
    group: 'Console',
    summary: 'change how the console looks and behaves, in place',
    steps: [
      { text: 'Open Settings (key s). Each row is edited right there.', go: { view: 'settings' } },
      { text: 'look: bbs is the neon look, plain uses your terminal’s own colours. boot turns the intro on or off.' },
      { text: 'fps sets how fast things move: 0 turns motion off, 12 is the most.' },
      { text: 'panel decides whether the cockpit opens by itself: auto, only on /ruflo, or never.' },
      { text: 'More options (how often the disk is re-read, the band above the prompt) are listed under the plugin’s options.' },
      { text: 'Pick ruflo-mods to see its switches: budget, hard stop, tool hints, hiding unused agent types (agentTrim) and screening peer deliveries (deliveryScreen). The last three are off by default, and each change asks for your Yes.' },
    ],
    tips: ['On a slow connection or a small window, set look to plain and fps to 0.'],
    related: ['updates', 'cost'],
    keywords: ['look', 'fps', 'boot', 'theme', 'plain', 'lite', 'motion', 'options', 'config'],
  },
  {
    id: 'updates',
    title: 'Update the console',
    group: 'Console',
    summary: 'new versions are offered when you start a session',
    steps: [
      { text: 'When a new version is published, the console asks at load: Update now, Always auto-update, or Not now.' },
      { text: 'Always auto-update installs new minor and patch versions without asking. A new major version always asks.' },
      { text: 'Settings has an Updates row: choose ask or auto, and press “check for an update now”.', go: { view: 'settings' } },
      { text: 'Restart Claude Code after an update so the new version loads.' },
    ],
    related: ['settings', 'plugins'],
    keywords: ['version', 'upgrade', 'newer', 'auto-update'],
  },
  {
    id: 'headless',
    title: 'Commands without the pane',
    group: 'Console',
    summary: '/ruflo works from any session, and from scripts',
    steps: [
      { text: '/ruflo opens the cockpit. /ruflo <page> goes to a page, for example /ruflo swarm.' },
      { text: '/ruflo run <entry> [text] runs a palette entry, for example /ruflo run spawn-coder.' },
      { text: '/ruflo yes and /ruflo no answer a pending confirm without the pane.' },
      { text: '/ruflo dump <page> prints a page as plain text, for scripts and claude -p.' },
      { text: '/ruflo status gives a one-line summary. /ruflo commands browses every ruflo command.' },
    ],
    related: ['keys'],
    keywords: ['slash', 'command', 'script', 'headless', 'cli', 'dump'],
  },
  {
    id: 'verify',
    title: 'Check that it really works',
    group: 'Console',
    summary: 'a connection is not proof: run something and look at the result',
    steps: [
      { text: 'Run the doctor: Node, git, config, the daemon, memory, API keys and MCP.', go: { view: 'secure' }, label: 'Open Security & Doctor' },
      { text: 'See the tools your assistant can reach: npx ruflo mcp tools. Call one harmless one: npx ruflo mcp exec --tool system_health.' },
      { text: 'Check the daemon.', go: { run: 'auto-daemon-status' } },
      { text: 'Save a small receipt: the tool, what you gave it, the result, the time, the cost and any test evidence. Repeat it in a fresh session.' },
    ],
    tips: ['A registered agent or a task record is not evidence the work ran.', '“unknown” from a check means not proven, not healthy. doctor --fix prints suggestions; it does not repair everything.'],
    related: ['troubleshoot', 'connect', 'security'],
    keywords: ['verify', 'check', 'test', 'health', 'proof', 'working', 'evidence', 'receipt', 'doctor', 'mcp'],
  },
  {
    id: 'troubleshoot',
    title: 'Something is empty or not working',
    group: 'Console',
    summary: 'the usual causes, and the fix for each',
    steps: [
      { text: 'A page is empty or still reading: press r to refresh. A new project has little to show until you start something.' },
      { text: 'Nothing happens in a project: ruflo may not be set up there. Initialise it.', go: { start: 'init' } },
      { text: 'A plugin is missing or its marketplace is old: update the marketplace on Plugins, then restart Claude.', go: { view: 'plugins' } },
      { text: 'Check the install with Doctor: Node, git, config, the daemon, memory and API keys.', go: { view: 'secure' } },
      { text: 'The keys do nothing: click the pane once, then use them. The footer says “keys on” when it has them.' },
    ],
    tips: ['Still stuck? Press ✦ Ask Claude on the page, or ask ruHelp above.', 'Report bugs at github.com/ruvnet/ruflo/issues.'],
    related: ['verify', 'setup', 'plugins'],
    keywords: ['fix', 'broken', 'error', 'empty', 'wrong', 'problem', 'stuck', 'nothing', 'not working'],
  },
]
